[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
crowd_funding = "FVVTSH5xRtir25Eq28KHsn9jQffBJ5NE1GZJgnPYPTXW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/vaishalichandrashekhar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
